### ISSUE TITLE
B: Upload error 

### ISSUE THREAD

**Issue by adammaclaren** [KingdomFirst/Bulldozer#23]
I am running Rock McKinley 8.8
I am using Rock.dll v1.8.8.3
Running windows 10 pro
SQL Server 11.0.7001.0

Any help would be appreciated. 

![1](https://user-images.githubusercontent.com/53626395/68971180-985a9a80-07ae-11ea-9263-25f48481b7b6.jpg)
![2](https://user-images.githubusercontent.com/53626395/68971194-a0b2d580-07ae-11ea-9924-3614de84a6ff.jpg)
![3](https://user-images.githubusercontent.com/53626395/68971203-a3152f80-07ae-11ea-8794-dea4a436bc8a.jpg)
![4](https://user-images.githubusercontent.com/53626395/68971209-a4def300-07ae-11ea-938e-58fdf138a810.jpg)

**Comment by nateh777** [comment]
What version of Bulldozer are you running? We just released v1.9.2.5.20191114 which had Rock version 9 specific changes in it, be sure you are running a previous release of Bulldozer: https://github.com/KingdomFirst/Bulldozer/releases. 

As for the actual error, it looks like it is not connected to the proper database or doesn't have the proper permission, it cannot find the database table "DefinedValue" in your database.

**Comment by adammaclaren** [comment]
I am running v1.8.8.3 as my version of rock is also older. Is that correct
or should I update anyways and update rock at the same time?

On the screen before the error, when I click to connect to the rock server
it says it successfully connected to the Rock database as well.

Any further thoughts?

**Comment by mattbaylor** [comment]
@adammaclaren try the release at this link: https://github.com/KingdomFirst/Bulldozer/tree/v1.8.8.3.20190919

**Comment by mattbaylor** [comment]
@adammaclaren Or did I misunderstand that the release at the link above is the version of Bulldozer you are using and you are still getting an error?

**Comment by adammaclaren** [comment]
Perhaps clarify for me just so that we are on the same page. In the
bulldozer app, at the bottom, it says using Rock.dllv1.8.8.3. Is that the
Bulldozer version or the Rock version it is connecting to?

Would it be better if I updated everything to the newest version and
started from there?

**Comment by nateh777** [comment]
@adammaclaren Sorry, you are correct, that should show which version you are running Bulldozer with, which in turn matches the bulldozer version generally. I would verify you are able to connect to your database and select from dbo.DefinedValue with the same connection settings, unfortunately that is all I see from the error. After that I would re-verify the data you are attempting to import and ensure it matches the examples given or review the documentation and/or wiki for any notes on the data import. If you do that and it still gives you a different error be sure to let us know what it is now, if it still gives you the same error I would slowly eliminate each file until you narrow down which one is causing the issue.

**Comment by adammaclaren** [comment]
Thanks, I have updated everything to V1.9.2.5 to eliminate that. Still getting the same error. I see this person had a similar issue with Bulldozer but no final say on results. https://github.com/KingdomFirst/Excavator/issues/195

I am able to connect to my database through the SQL server management studio. My server name is o-db though, would that be affecting it? I had a volunteer set it up so I am uncertain if perhaps there are other practices used for naming or if this should even make a difference. What is odd to me is that it worked, once and since then hasn't. 

I am currently just using the individual CSV sample file so it shouldn't be on that side of it.

**Comment by nateh777** [comment]
To me it just seems like something is up with your database connection, it isn't connecting to the proper database somehow or a custom schema as referenced in that old issue.

Check your database connection and ensure you actually do have `DefinedValue` in your database. 

To check your database connection compare your web.ConnectionStrings.config and compare the Bulldozer.exe.config (after you attempt to run it should be updated) and see if line 22 matches for RockContext. Simple test for the database would be test this query through sql management studio: `SELECT TOP 1000 * FROM [dbo].[DefinedValue]` and ensure it works. (This is assuming your connection through studio is the same as what Bulldozer is using which can be hard as mine is through windows authentication on one and sql authentication on another.)

**Comment by adammaclaren** [comment]
You were correct, I found it was a credential issue that reset from my test that worked. Thanks for you help. Got it!
